### PR TITLE
Fix  #102 - Split Zipkin code into multiple maven modules.

### LINKED ISSUE #102: Cleanup zipkin transport dependencies
Currently inclusion of zipkin triggers inclusion of socket and jetty transports. This is bad for clients and less than ideal for servers. Additionally whilst we can exclude dependencies, certain config will fail if we do (for example socket port which if socket transport not included will fail to parse to an int and throw and exception at start).

This needs resolving prior to 3.3 release.

### PR DESCRIPTION
**Pull request by andredasilvapinto**
So we can include more limited dependencies into the projects that use it.

E.g.:
```
<dependency>
  <groupId>com.betfair.cougar</groupId>
  <artifactId>cougar-zipkin-server-http</artifactId>
  <version>${cougar.version}</version>
</dependency>

<dependency>
  <groupId>com.betfair.cougar</groupId>
  <artifactId>cougar-zipkin-client-http</artifactId>
  <version>${cougar.version}</version>
</dependency>
```

for HTTP support, plus importing the resources to Spring's Application Context:
```
<import resource="classpath:conf/cougar-zipkin-server-http.xml"/>
<import resource="classpath:conf/cougar-zipkin-client-http.xml"/>
```

Tested by @HugoMFernandes

### CODE REVIEW

**Comment by eswdd** [comment]
Looks sane on phone. Travis build due to other issues failed so will merge manually and review more thoroughly...

**Comment by eswdd** [comment]
Would it be safe to assume you want a release cut after this?

**Comment by andredasilvapinto** [comment]
hey Simon, for me it isn't really relevant, I just wanted to help finish the Zipkin feature, as it would be a waste to have it unfinished just because of this.

**Comment by eswdd** [comment]
Ah yes, sorry, I'd forgotten you've left Betfair.

**Comment by HugoMFernandes** [comment]
We still have a couple of services running cougar 3, so we could use a release cut. Thanks @andredasilvapinto for finishing this.

**Pull request merged**
